version: "3.7"
services:
  vote:
    build:
      context: ./vote
    deploy :
      mode : global
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - voting-app

  worker:
    build:
      context: ./worker
    deploy :
      mode : global
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    networks:
      - voting-app

  result:
    build:
      context: ./result
    deploy :
      mode : global
    ports:
      - 8081:8888
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    networks:
      - voting-app

  redis:
    image: redis:latest
    deploy :
      mode : global
    ports:
      - 6379:6379
    depends_on:
      - worker
    networks:
      - voting-app

  postgres:
    image: postgres:latest
    deploy :
      mode : global
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - voting-app

volumes:
  pg-data:
    external: true
      
networks:
  voting-app:

